# Generated by Django 4.0.10 on 2024-05-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='vendordetail',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='vendordetaillog',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='vendorperformance',
            options={'ordering': ('-creation_date',)},
        ),
    ]
