# Generated by Django 4.0.10 on 2024-05-07 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='average_response_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='fulfillment_rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='on_time_delivery_rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendordetail',
            name='quality_rating_avg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='average_response_time',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='fulfillment_rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='on_time_delivery_rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='quality_rating_avg',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.DeleteModel(
            name='VendorDetailLog',
        ),
    ]
