# Generated by Django 4.0.10 on 2024-05-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_alter_purchaseorder_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorperformance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vendor_performance', to='vendor_app.vendordetail'),
        ),
    ]
